---
title: "perianal_ewas_rev"
author: "Takeo Naito, MD PhD"
date: "8/8/2019"
output: html_document
---




```{r}
library(tidyverse)
library(readxl)
library(data.table)
library(readr)
library(knitr)
library(kableExtra)
```
# prepare adimix file and target file(include perianal information)

```{r}
admix <- fread("/mnt/share6/FOR_Takeo/array_139/admix_with_jewish_nonjewish_prop_added.txt")

target <- fread("/mnt/share6/FOR_Takeo/WES/SKAT/SKAT_target_rev2.txt") %>% 
  select(IID,GeneticID,anal)
target$GeneticID <- str_replace(target$GeneticID,"-","0")
```
# read phenotype file which includes Race information (self reported)

```{r}
pheno <- read_xls("../data/Copy of Genetics 01_02_2019.xls",col_types = "text")
colnames(pheno) <- make.names(colnames(pheno))
pheno <- pheno %>% 
  distinct(Genetic.ID, .keep_all = TRUE) %>% 
  select(Genetic.ID, Race)
pheno$Genetic.ID <- str_replace(pheno$Genetic.ID,"-","0")
```

```{r}
target <- target %>% 
  left_join(pheno,by=c("GeneticID" = "Genetic.ID"))

```
# merge each file and extract only Caucasian (self reported)

```{r}
target1 <- target %>% 
  inner_join(admix,by = c("GeneticID" = "FID")) %>% 
  filter(anal != -9) %>% 
  filter(Race == "Caucasian")
```

# Some outlier exist

```{r}
ggplot(target1,aes(Caucasian)) + geom_histogram()
```



# filter by admix Caucasian
```{r}
target2 <- target1 %>% 
  filter(Caucasian >= 0.75)
```
# Check outlier's (Caucasian by self reported but not Caucasian by admixture )
```{r}
outlier <- target1 %>% 
  filter(Caucasian < 0.75)

dim(outlier)
outlier
```

# select only Caucasian by admixture

```{r}
target2 %>% 
  select(IID.x) %>% 
  write_tsv("../data/caucasian_admix.txt",col_names = FALSE)
```


```{bash}
plink2 \
--bfile ../data/cleaned_cedars_bialle \
--exclude range ../data/highLDregions.txt \
--geno 0.01 \
--indep-pairwise 50 5 0.1 \
--keep ../data/caucasian_admix.txt \
--maf 0.05 \
--mind 0.01 \
--not-chr X Y \
--out ../filtering/hail/cleaned_cedars_cauc_rev

```


```{bash}
plink2 \
--bfile ../data/cleaned_cedars_bialle \
--extract ../filtering/hail/cleaned_cedars_cauc_rev.prune.in \
--keep ../data/caucasian_admix.txt \
--out ../filtering/hail/PCAclean_cauc_rev \
--pca 5 \
--threads 10
```



```{bash}
plink2 \
--covar ../filtering/hail/PCAclean_cauc_rev.eigenvec \
--covar-col-nums 3,4,5,6 \
--logistic hide-covar \
--out ../result/anal_rev \
--bfile ../data/cleaned_cedars \
--pheno /mnt/share6/FOR_Takeo/WES/SKAT/SKAT_target_rev2.txt \
--pheno-col-nums 29 \
--keep ../data/caucasian_admix.txt \
--hwe 0.01 \
--adjust \
--threads 4
```
```{bash}
plink2 \
--keep-if anal = 2 \
--freq \
--out ../result/case_rev \
--bfile ../data/cleaned_cedars \
--keep ../data/caucasian_admix.txt \
--pheno /mnt/share6/FOR_Takeo/WES/SKAT/SKAT_target_rev2.txt 
```


```{bash}
plink2 \
--keep-if anal = 1 \
--freq \
--out ../result/cnt_rev \
--bfile ../data/cleaned_cedars \
--keep ../data/caucasian_admix.txt \
--pheno /mnt/share6/FOR_Takeo/WES/SKAT/SKAT_target_rev2.txt 
```

```{r}
res <- fread("../result/anal_rev.anal.glm.logistic") %>% 
  arrange(P)

casefre <- fread("../result/case_rev.afreq")
colnames(casefre) <- make.names(colnames(casefre))

cntfre <- fread("../result/cnt_rev.afreq")
colnames(cntfre) <- make.names(colnames(cntfre))

```


```{r}
merge1 <- casefre %>% 
  inner_join(cntfre,by = "ID") %>% 
  select(-X.CHROM.y,-REF.y,-ALT.y)


merge2 <- res %>% 
  inner_join(merge1,by = "ID") %>% 
  select(X.CHROM.x, POS, REF,ALT,OBS_CT,OR,P,ALT_FREQS.x,OBS_CT.x,
         ALT_FREQS.y,OBS_CT.y) %>%  
  dplyr::rename(CHR =  X.CHROM.x, freq_case = ALT_FREQS.x, freq_cnt = ALT_FREQS.y,
         total_n = OBS_CT, case_n = OBS_CT.x, cnt_n = OBS_CT.y) %>% 
  mutate(case_n = case_n/2, cnt_n = cnt_n/2)
```


```{r}
kable(head(merge2,10)) %>%
  kable_styling() %>%
  scroll_box(width = "800px", height = "200px")
```

```{r}
head(merge2)
```


```{bash}
plink2 \
--covar ../filtering/hail/PCAclean_cauc_rev.eigenvec \
--covar-col-nums 3,4,5,6 \
--logistic hide-covar \
--out ../result/anal_chr20_rev \
--bfile ../data/cleaned_cedars \
--pheno /mnt/share6/FOR_Takeo/WES/SKAT/SKAT_target_rev2.txt \
--pheno-col-nums 29 \
--keep ../data/caucasian_admix.txt \
--chr 20 \
--from-mb 55 \
--to-mb 56 \
--threads 4


plink2 \
--covar ../filtering/hail/PCAclean_cauc_rev.eigenvec \
--covar-col-nums 3,4,5,6 \
--logistic hide-covar \
--out ../result/anal_chr20 \
--bfile ../data/cleaned_cedars \
--pheno /mnt/share6/FOR_Takeo/WES/SKAT/SKAT_target_rev2.txt \
--pheno-col-nums 29 \
--keep ../data/caucasian.txt \
--chr 20 \
--from-mb 55 \
--to-mb 56 \
--threads 4
```

